# Generated by Django 4.0.2 on 2022-02-11 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organism', models.CharField(max_length=150, null=True, verbose_name='Nom Organisme')),
                ('auteur', models.CharField(max_length=50, null=True, verbose_name='Auteur')),
                ('profil', models.ImageField(null=True, upload_to='profil/', verbose_name='Profil')),
                ('cel', models.CharField(max_length=20, null=True, verbose_name='Contact Whatsapp')),
            ],
            options={
                'verbose_name_plural': 'Catégorie des Videos',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleV', models.CharField(max_length=255, unique=True, verbose_name='Titre Video')),
                ('content', models.TextField(null=True, verbose_name='Description Vidéo')),
                ('url', embed_video.fields.EmbedVideoField(unique=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.category', verbose_name='Categories Videos')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Nos Videos',
                'ordering': ['-added'],
            },
        ),
    ]
