# Generated by Django 4.0.2 on 2022-02-08 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PubHt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='Titre')),
                ('urls', models.URLField(verbose_name='Url')),
                ('content', models.TextField(verbose_name='Contenu Pub')),
                ('bannerHt', models.ImageField(null=True, upload_to='pub/', verbose_name='Pub Format 728x90')),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicité Format 728x90',
                'ordering': ['-date_add'],
            },
        ),
        migrations.CreateModel(
            name='PubGt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_t', models.CharField(max_length=100, null=True, verbose_name='Titre')),
                ('urls_t', models.URLField(verbose_name='Url')),
                ('content_t', models.TextField(verbose_name='Contenu Pub')),
                ('bannerGt', models.ImageField(null=True, upload_to='pub/', verbose_name='Pub Format 702x1029')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicité Format 702x1029',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='logoOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titl_lo', models.CharField(max_length=100, null=True, verbose_name='Titre du Logo')),
                ('logos', models.ImageField(upload_to='logo/', verbose_name='Image Logo')),
                ('date_Reg', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logo Organisme',
                'ordering': ['-date_Reg'],
            },
        ),
    ]
